### ISSUE TITLE
Not able to see annotations with colors from browser

### ISSUE THREAD

**Issue by krishnareddyML** [GateNLP/gateplugin-Format_HTML5Microdata#1]
[ft-bank-of-uk-08-Aug-2001.html.txt](https://github.com/GateNLP/gateplugin-Format_HTML5Microdata/files/3661013/ft-bank-of-uk-08-Aug-2001.html.txt)
I tried to use this plugin to export sample annotated document to html5 micro data format from GATE GUI. But when I open html file in browser I am not seeing any annotations with colors. Is there anything I am missing about this plugin ?

**Comment by krishnareddyML** [comment]
My thoughts about this plugin usage may be wrong, please let me  know usage of this plugin. I believe this will export annotations in html format with CSS and then we can easily see annotations with colors in browser as we see in GATE GUI.

**Comment by greenwoodma** [comment]
The plugin was originally designed to simply embed HTML5 Microdata that used the schemas from [schema.org](https://schema.org/). The purpose of this is not to highlight annotations visibly for humans (in the way the GATE GUI does) but to make them machine readable, as Google and others use HTML5 Microdata when indexing pages.

Having said that it is possible to add CSS to the files generated by this plugin to make them human visible as well. Let's take a small example to show what I mean.

```David works in Sheffield```

When processed by ANNIE has a `Person` and a `Location` annotation over _David_ and _Sheffield_ respectively. If we then export using this plugin we get the following HTML

```<html><body><span itemscope="itemscope" itemtype="http://schema.org/Person"><meta itemprop="gender" content="male"/><meta itemprop="name" content="David"/>David</span> works in <span itemscope="itemscope" itemtype="http://schema.org/City"><meta itemprop="name" content="Sheffield"/>Sheffield</span>.</body></html>```

What you can see is that each annotation is surrounded by  a `span` element that has both `itemscope` and `itemtype` attributes. Features of the annotations are also included as `meta` elements in the XML structure. We can use the `itemtype` attribute as a CSS selector to apply relevant styles. So to colour the people red and the locations green we would expand this to the following

```<html><head>
<style>
[itemtype="http://schema.org/Person"] {
	color: red;
}

[itemtype="http://schema.org/City"] {
	color: green;
}
</style>
</head><body><span itemscope="itemscope" itemtype="http://schema.org/Person"><meta itemprop="gender" content="male"/><meta itemprop="name" content="David"/>David</span> works in <span itemscope="itemscope" itemtype="http://schema.org/City"><meta itemprop="name" content="Sheffield"/>Sheffield</span>.</body></html>
```

We don't add the CSS when exporting the documents because we have no way of knowing what styles would be appropriate, but more importantly because, as I said at the start, our original use case for this plugin was to only produce machine readable data; i.e. the annotations weren't meant to be visible to humans.

**Comment by krishnareddyML** [comment]
Thank you for making me understand real usage of plugin.
